# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(20, 140, 93, 91))
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(130, 140, 93, 91))
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(240, 140, 93, 91))
        self.btn9.setObjectName("btn9")
        self.btndiv = QtWidgets.QPushButton(self.centralwidget)
        self.btndiv.setGeometry(QtCore.QRect(350, 140, 93, 91))
        self.btndiv.setObjectName("btndiv")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(240, 240, 93, 91))
        self.btn6.setObjectName("btn6")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(130, 240, 93, 91))
        self.btn5.setObjectName("btn5")
        self.btnmul = QtWidgets.QPushButton(self.centralwidget)
        self.btnmul.setGeometry(QtCore.QRect(350, 240, 93, 91))
        self.btnmul.setObjectName("btnmul")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(20, 240, 93, 91))
        self.btn4.setObjectName("btn4")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(240, 340, 93, 91))
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(130, 340, 93, 91))
        self.btn2.setObjectName("btn2")
        self.btnplus = QtWidgets.QPushButton(self.centralwidget)
        self.btnplus.setGeometry(QtCore.QRect(350, 440, 93, 91))
        self.btnplus.setObjectName("btnplus")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(20, 340, 93, 91))
        self.btn1.setObjectName("btn1")
        self.btneq = QtWidgets.QPushButton(self.centralwidget)
        self.btneq.setGeometry(QtCore.QRect(240, 440, 93, 91))
        self.btneq.setObjectName("btneq")
        self.btnc = QtWidgets.QPushButton(self.centralwidget)
        self.btnc.setGeometry(QtCore.QRect(130, 440, 93, 91))
        self.btnc.setObjectName("btnc")
        self.btnce = QtWidgets.QPushButton(self.centralwidget)
        self.btnce.setGeometry(QtCore.QRect(20, 440, 93, 91))
        self.btnce.setObjectName("btnce")
        self.btnmin = QtWidgets.QPushButton(self.centralwidget)
        self.btnmin.setGeometry(QtCore.QRect(350, 340, 93, 91))
        self.btnmin.setObjectName("btnmin")
        self.txtbox = QtWidgets.QLineEdit(self.centralwidget)
        self.txtbox.setGeometry(QtCore.QRect(20, 20, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.txtbox.setFont(font)
        self.txtbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtbox.setObjectName("txtbox")
        self.lblsub = QtWidgets.QLabel(self.centralwidget)
        self.lblsub.setGeometry(QtCore.QRect(370, 30, 55, 16))
        self.lblsub.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblsub.setObjectName("lblsub")

        self.answer = self.val1 = self.val2 = None

        #Button Actions
        self.btn1.clicked.connect(self.click_btn1)
        self.btn2.clicked.connect(self.click_btn2)
        self.btn3.clicked.connect(self.click_btn3)
        self.btn4.clicked.connect(self.click_btn4)
        self.btn5.clicked.connect(self.click_btn5)
        self.btn6.clicked.connect(self.click_btn6)
        self.btn7.clicked.connect(self.click_btn7)
        self.btn8.clicked.connect(self.click_btn8)
        self.btn9.clicked.connect(self.click_btn9)

        self.btnplus.clicked.connect(self.math_add)
        self.btnmin.clicked.connect(self.math_min)
        self.btnmul.clicked.connect(self.math_mul)
        self.btndiv.clicked.connect(self.math_div)

        self.btneq.clicked.connect(self.calc)
        self.btnce.clicked.connect(self.btn_ce)
        self.btnc.clicked.connect(self.btn_c)


        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnce, self.btnc)
        MainWindow.setTabOrder(self.btnc, self.btneq)
        MainWindow.setTabOrder(self.btneq, self.btnplus)
        MainWindow.setTabOrder(self.btnplus, self.btn1)
        MainWindow.setTabOrder(self.btn1, self.btn2)
        MainWindow.setTabOrder(self.btn2, self.btn3)
        MainWindow.setTabOrder(self.btn3, self.btnmin)
        MainWindow.setTabOrder(self.btnmin, self.btn4)
        MainWindow.setTabOrder(self.btn4, self.btn5)
        MainWindow.setTabOrder(self.btn5, self.btn6)
        MainWindow.setTabOrder(self.btn6, self.btnmul)
        MainWindow.setTabOrder(self.btnmul, self.btn7)
        MainWindow.setTabOrder(self.btn7, self.btn8)
        MainWindow.setTabOrder(self.btn8, self.btn9)
        MainWindow.setTabOrder(self.btn9, self.btndiv)
        MainWindow.setTabOrder(self.btndiv, self.txtbox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Teskill Sample Calculator v1"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btndiv.setText(_translate("MainWindow", "/"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btnmul.setText(_translate("MainWindow", "*"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btnplus.setText(_translate("MainWindow", "+"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btneq.setText(_translate("MainWindow", "="))
        self.btnc.setText(_translate("MainWindow", "C"))
        self.btnce.setText(_translate("MainWindow", "CE"))
        self.btnmin.setText(_translate("MainWindow", "-"))
        self.txtbox.setText(_translate("MainWindow", ""))
        self.lblsub.setText(_translate("MainWindow", ""))

    def setText(self,value):
        self.cText = str(self.txtbox.text())
        self.txtbox.setText(str(self.cText+str(value)))

    def click_btn1(self):
        self.setText(1)
    def click_btn2(self):
        self.setText(2)
    def click_btn3(self):
        self.setText(3)
    def click_btn4(self):
        self.setText(4)
    def click_btn5(self):
        self.setText(5)
    def click_btn6(self):
        self.setText(6)
    def click_btn7(self):
        self.setText(7)
    def click_btn8(self):
        self.setText(8)
    def click_btn9(self):
        self.setText(9)

    def math_add(self):
        self.mark = '+'
        self.val1 = str(self.txtbox.text())
        self.txtbox.setText('')
        self.lblsub.setText(str(str(self.val1)+self.mark))
    def math_min(self):
        self.mark = '-'
        self.val1 = str(self.txtbox.text())
        self.txtbox.setText('')
        self.lblsub.setText(str(str(self.val1)+self.mark))
    def math_mul(self):
        self.mark = '*'
        self.val1 = str(self.txtbox.text())
        self.txtbox.setText('')
        self.lblsub.setText(str(str(self.val1)+self.mark))
    def math_div(self):
        self.mark = '/'
        self.val1 = str(self.txtbox.text())
        self.txtbox.setText('')
        self.lblsub.setText(str(str(self.val1)+self.mark))
    
    def calc(self):
        try:
            self.val1 = float(self.val1)
            self.val2 = float(self.txtbox.text())

            if self.mark == '+':
                self.answer = self.val1+self.val2
            elif self.mark == '-':
                self.answer = self.val1-self.val2
            elif self.mark == '*':
                self.answer = self.val1*self.val2
            elif self.mark == '/':
                try:
                    self.answer = self.val1/self.val2
                except ZeroDivisionError:
                    self.answer = 'Zero Division Error'
        except:
            self.answer= 'Invalid Number'

        self.lblsub.setText(str(self.lblsub.text()+str(self.val2)))
        self.txtbox.setText(str(self.answer))
    def btn_ce(self):
        self.answer = None
        self.val1 = self.val2 =None
        self.txtbox.setText('')
        self.lblsub.settext('')
    def btn_c(self):
        self.val2 = None
        self.txtbox.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
